-- =============================================================================
-- Migration 0006 — Replace UNIQUE(session_date) on km_sessions with
--                  UNIQUE(user_id, session_date) for multi-user ownership.
--
-- Context:
--   0001 created km_sessions with session_date NOT NULL UNIQUE — one session
--   per date globally. After 0005 added user_id, each user has their own
--   session per date. The old UNIQUE constraint breaks inserts when two users
--   record a session on the same date.
--
-- Prereqs: 0001, 0005 (user_id column must exist on km_sessions)
-- =============================================================================

-- 1. Drop the old inline UNIQUE constraint on session_date.
--    The constraint name is auto-generated by PG as km_sessions_session_date_key.
--    IF EXISTS guard makes this idempotent.
ALTER TABLE km_sessions
    DROP CONSTRAINT IF EXISTS km_sessions_session_date_key;

-- 2. Add composite unique index: one session per (user, date).
--    Partial index excludes rows where user_id IS NULL (pre-auth legacy rows
--    from 0001 era) so they don't conflict with each other or new rows.
CREATE UNIQUE INDEX IF NOT EXISTS idx_km_sessions_user_date_unique
    ON km_sessions (user_id, session_date)
    WHERE user_id IS NOT NULL;
